extraction:
  cpp:
    prepare:
      packages:
        - libmysqlclient-dev
        - unixodbc-dev
        - libpq-dev
    after_prepare:
      - PATH="$HOME/.local/bin:$PATH"
      - pip3 install --upgrade setuptools wheel
      - pip3 install --upgrade meson
    configure:
      command:
        - meson build
    index:
      build_command:
        - ninja -C build
queries:
  - include: "*"
  - exclude: cpp/loop-variable-changed
  - exclude: cpp/commented-out-code
  - include: cpp/todo-comment
